swagger: '2.0'
info:
  title: HTTP API Console — cosmos-distribution
  name: ''
  description: ''
paths:
  /cosmos/distribution/v1beta1/community_pool:
    get:
      summary: CommunityPool queries the community pool coins.
      operationId: CosmosDistributionV1Beta1CommunityPool
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              pool:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    amount:
                      type: string
                  description: 'DecCoin defines a token with a denomination and a
                    decimal amount.


                    NOTE: The amount field is an Dec which implements the custom method

                    signatures required by gogoproto.'
                description: pool defines community pool's coins.
            description: 'QueryCommunityPoolResponse is the response type for the
              Query/CommunityPool

              RPC method.'
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
      - Query
  /cosmos/distribution/v1beta1/delegators/{delegator_address}/rewards:
    get:
      summary: 'DelegationTotalRewards queries the total rewards accrued by a each

        validator.'
      operationId: CosmosDistributionV1Beta1DelegationTotalRewards
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              rewards:
                type: array
                items:
                  type: object
                  properties:
                    validator_address:
                      type: string
                    reward:
                      type: array
                      items:
                        type: object
                        properties:
                          denom:
                            type: string
                          amount:
                            type: string
                        description: 'DecCoin defines a token with a denomination
                          and a decimal amount.


                          NOTE: The amount field is an Dec which implements the custom
                          method

                          signatures required by gogoproto.'
                  description: 'DelegationDelegatorReward represents the properties

                    of a delegator''s delegation reward.'
                description: rewards defines all the rewards accrued by a delegator.
              total:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    amount:
                      type: string
                  description: 'DecCoin defines a token with a denomination and a
                    decimal amount.


                    NOTE: The amount field is an Dec which implements the custom method

                    signatures required by gogoproto.'
                description: total defines the sum of all the rewards.
            description: 'QueryDelegationTotalRewardsResponse is the response type
              for the

              Query/DelegationTotalRewards RPC method.'
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
      - name: delegator_address
        description: delegator_address defines the delegator address to query for.
        in: path
        required: true
        type: string
      tags:
      - Query
  /cosmos/distribution/v1beta1/delegators/{delegator_address}/rewards/{validator_address}:
    get:
      summary: DelegationRewards queries the total rewards accrued by a delegation.
      operationId: CosmosDistributionV1Beta1DelegationRewards
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              rewards:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    amount:
                      type: string
                  description: 'DecCoin defines a token with a denomination and a
                    decimal amount.


                    NOTE: The amount field is an Dec which implements the custom method

                    signatures required by gogoproto.'
                description: rewards defines the rewards accrued by a delegation.
            description: 'QueryDelegationRewardsResponse is the response type for
              the

              Query/DelegationRewards RPC method.'
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
      - name: delegator_address
        description: delegator_address defines the delegator address to query for.
        in: path
        required: true
        type: string
      - name: validator_address
        description: validator_address defines the validator address to query for.
        in: path
        required: true
        type: string
      tags:
      - Query
  /cosmos/distribution/v1beta1/delegators/{delegator_address}/validators:
    get:
      summary: DelegatorValidators queries the validators of a delegator.
      operationId: CosmosDistributionV1Beta1DelegatorValidators
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              validators:
                type: array
                items:
                  type: string
                description: validators defines the validators a delegator is delegating
                  for.
            description: 'QueryDelegatorValidatorsResponse is the response type for
              the

              Query/DelegatorValidators RPC method.'
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
      - name: delegator_address
        description: delegator_address defines the delegator address to query for.
        in: path
        required: true
        type: string
      tags:
      - Query
  /cosmos/distribution/v1beta1/delegators/{delegator_address}/withdraw_address:
    get:
      summary: DelegatorWithdrawAddress queries withdraw address of a delegator.
      operationId: CosmosDistributionV1Beta1DelegatorWithdrawAddress
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              withdraw_address:
                type: string
                description: withdraw_address defines the delegator address to query
                  for.
            description: 'QueryDelegatorWithdrawAddressResponse is the response type
              for the

              Query/DelegatorWithdrawAddress RPC method.'
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
      - name: delegator_address
        description: delegator_address defines the delegator address to query for.
        in: path
        required: true
        type: string
      tags:
      - Query
  /cosmos/distribution/v1beta1/params:
    get:
      summary: Params queries params of the distribution module.
      operationId: CosmosDistributionV1Beta1Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                description: params defines the parameters of the module.
                type: object
                properties:
                  community_tax:
                    type: string
                  base_proposer_reward:
                    type: string
                  bonus_proposer_reward:
                    type: string
                  withdraw_addr_enabled:
                    type: boolean
            description: QueryParamsResponse is the response type for the Query/Params
              RPC method.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
      - Query
  /cosmos/distribution/v1beta1/validators/{validator_address}/commission:
    get:
      summary: ValidatorCommission queries accumulated commission for a validator.
      operationId: CosmosDistributionV1Beta1ValidatorCommission
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              commission:
                description: commission defines the commision the validator received.
                type: object
                properties:
                  commission:
                    type: array
                    items:
                      type: object
                      properties:
                        denom:
                          type: string
                        amount:
                          type: string
                      description: 'DecCoin defines a token with a denomination and
                        a decimal amount.


                        NOTE: The amount field is an Dec which implements the custom
                        method

                        signatures required by gogoproto.'
            title: 'QueryValidatorCommissionResponse is the response type for the

              Query/ValidatorCommission RPC method'
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
      - name: validator_address
        description: validator_address defines the validator address to query for.
        in: path
        required: true
        type: string
      tags:
      - Query
  /cosmos/distribution/v1beta1/validators/{validator_address}/outstanding_rewards:
    get:
      summary: ValidatorOutstandingRewards queries rewards of a validator address.
      operationId: CosmosDistributionV1Beta1ValidatorOutstandingRewards
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              rewards:
                type: object
                properties:
                  rewards:
                    type: array
                    items:
                      type: object
                      properties:
                        denom:
                          type: string
                        amount:
                          type: string
                      description: 'DecCoin defines a token with a denomination and
                        a decimal amount.


                        NOTE: The amount field is an Dec which implements the custom
                        method

                        signatures required by gogoproto.'
                description: 'ValidatorOutstandingRewards represents outstanding (un-withdrawn)
                  rewards

                  for a validator inexpensive to track, allows simple sanity checks.'
            description: 'QueryValidatorOutstandingRewardsResponse is the response
              type for the

              Query/ValidatorOutstandingRewards RPC method.'
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
      - name: validator_address
        description: validator_address defines the validator address to query for.
        in: path
        required: true
        type: string
      tags:
      - Query
  /cosmos/distribution/v1beta1/validators/{validator_address}/slashes:
    get:
      summary: ValidatorSlashes queries slash events of a validator.
      operationId: CosmosDistributionV1Beta1ValidatorSlashes
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              slashes:
                type: array
                items:
                  type: object
                  properties:
                    validator_period:
                      type: string
                      format: uint64
                    fraction:
                      type: string
                  description: 'ValidatorSlashEvent represents a validator slash event.

                    Height is implicit within the store key.

                    This is needed to calculate appropriate amount of staking tokens

                    for delegations which are withdrawn after a slash has occurred.'
                description: slashes defines the slashes the validator received.
              pagination:
                description: pagination defines the pagination in the response.
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                    title: 'next_key is the key to be passed to PageRequest.key to

                      query the next page most efficiently'
                  total:
                    type: string
                    format: uint64
                    title: 'total is total number of results available if PageRequest.count_total

                      was set, its value is undefined otherwise'
            description: 'QueryValidatorSlashesResponse is the response type for the

              Query/ValidatorSlashes RPC method.'
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
      - name: validator_address
        description: validator_address defines the validator address to query for.
        in: path
        required: true
        type: string
      - name: starting_height
        description: starting_height defines the optional starting height to query
          the slashes.
        in: query
        required: false
        type: string
        format: uint64
      - name: ending_height
        description: starting_height defines the optional ending height to query the
          slashes.
        in: query
        required: false
        type: string
        format: uint64
      - name: pagination.key
        description: 'key is a value returned in PageResponse.next_key to begin

          querying the next page most efficiently. Only one of offset or key

          should be set.'
        in: query
        required: false
        type: string
        format: byte
      - name: pagination.offset
        description: 'offset is a numeric offset that can be used when key is unavailable.

          It is less efficient than using key. Only one of offset or key should

          be set.'
        in: query
        required: false
        type: string
        format: uint64
      - name: pagination.limit
        description: 'limit is the total number of results to be returned in the result
          page.

          If left empty it will default to a value to be set by each app.'
        in: query
        required: false
        type: string
        format: uint64
      - name: pagination.count_total
        description: 'count_total is set to true  to indicate that the result set
          should include

          a count of the total number of items available for pagination in UIs.

          count_total is only respected when offset is used. It is ignored when key

          is set.'
        in: query
        required: false
        type: boolean
      - name: pagination.reverse
        description: 'reverse is set to true if results are to be returned in the
          descending order.


          Since: cosmos-sdk 0.43'
        in: query
        required: false
        type: boolean
      tags:
      - Query
definitions: {}
