swagger: '2.0'
info:
  title: HTTP API Console — tendermint
  name: ''
  description: ''
paths:
  /tendermint/spn/monitoringp/connection_channel_id:
    get:
      summary: Queries a ConnectionChannelID by index.
      operationId: TendermintSpnMonitoringpConnectionChannelID
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              ConnectionChannelID:
                type: object
                properties:
                  channelID:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
      - Query
  /tendermint/spn/monitoringp/consumer_client_id:
    get:
      summary: Queries a ConsumerClientID by index.
      operationId: TendermintSpnMonitoringpConsumerClientID
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              ConsumerClientID:
                type: object
                properties:
                  clientID:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
      - Query
  /tendermint/spn/monitoringp/monitoring_info:
    get:
      summary: Queries a MonitoringInfo by index.
      operationId: TendermintSpnMonitoringpMonitoringInfo
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              MonitoringInfo:
                type: object
                properties:
                  transmitted:
                    type: boolean
                  signatureCounts:
                    type: object
                    properties:
                      blockCount:
                        type: string
                        format: uint64
                      counts:
                        type: array
                        items:
                          type: object
                          properties:
                            opAddress:
                              type: string
                            RelativeSignatures:
                              type: string
                          title: 'SignatureCount contains information of signature
                            reporting for one specific validator with consensus address

                            RelativeSignatures is the sum of all signatures relative
                            to the validator set size'
                    title: SignatureCounts contains information about signature reporting
                      for a number of blocks
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
      - Query
  /tendermint/spn/monitoringp/params:
    get:
      summary: Params queries the parameters of the module.
      operationId: TendermintSpnMonitoringpParams
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
                properties:
                  lastBlockHeight:
                    type: string
                    format: int64
                  consumerChainID:
                    type: string
                  consumerConsensusState:
                    type: object
                    properties:
                      nextValidatorsHash:
                        type: string
                      timestamp:
                        type: string
                      root:
                        type: object
                        properties:
                          hash:
                            type: string
                        title: MerkelRool represents a Merkel Root in ConsensusState
                    title: 'ConsensusState represents a Consensus State

                      it is compatible with the dumped state from `appd q ibc client
                      self-consensus-state` command'
                  consumerUnbondingPeriod:
                    type: string
                    format: int64
                  consumerRevisionHeight:
                    type: string
                    format: uint64
                description: Params defines the parameters for the module.
            description: QueryParamsResponse is response type for the Query/Params
              RPC method.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
      - Query
definitions: {}
